/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organizations: Organization;
    workspaces: Workspace;
    domains: Domain;
    'fallback-origins': FallbackOrigin;
    'fallback-url-safety-assessments': FallbackUrlSafetyAssessment;
    'organization-invitations': OrganizationInvitation;
    'organization-memberships': OrganizationMembership;
    subscriptions: Subscription;
    'billing-events': BillingEvent;
    'usage-counters': UsageCounter;
    apps: App;
    'deep-links': DeepLink;
    'abuse-reports': AbuseReport;
    'abuse-cases': AbuseCase;
    'enforcement-events': EnforcementEvent;
    'abuse-case-events': AbuseCaseEvent;
    'link-events': LinkEvent;
    'verification-runs': VerificationRun;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    workspaces: WorkspacesSelect<false> | WorkspacesSelect<true>;
    domains: DomainsSelect<false> | DomainsSelect<true>;
    'fallback-origins': FallbackOriginsSelect<false> | FallbackOriginsSelect<true>;
    'fallback-url-safety-assessments': FallbackUrlSafetyAssessmentsSelect<false> | FallbackUrlSafetyAssessmentsSelect<true>;
    'organization-invitations': OrganizationInvitationsSelect<false> | OrganizationInvitationsSelect<true>;
    'organization-memberships': OrganizationMembershipsSelect<false> | OrganizationMembershipsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'billing-events': BillingEventsSelect<false> | BillingEventsSelect<true>;
    'usage-counters': UsageCountersSelect<false> | UsageCountersSelect<true>;
    apps: AppsSelect<false> | AppsSelect<true>;
    'deep-links': DeepLinksSelect<false> | DeepLinksSelect<true>;
    'abuse-reports': AbuseReportsSelect<false> | AbuseReportsSelect<true>;
    'abuse-cases': AbuseCasesSelect<false> | AbuseCasesSelect<true>;
    'enforcement-events': EnforcementEventsSelect<false> | EnforcementEventsSelect<true>;
    'abuse-case-events': AbuseCaseEventsSelect<false> | AbuseCaseEventsSelect<true>;
    'link-events': LinkEventsSelect<false> | LinkEventsSelect<true>;
    'verification-runs': VerificationRunsSelect<false> | VerificationRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'deliver-cloud-account-email': TaskDeliverCloudAccountEmail;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super-admin' | 'admin' | 'viewer';
  status: 'active' | 'pending-verification' | 'disabled';
  allowedApps?: (number | App)[] | null;
  emailVerificationTokenHash?: string | null;
  emailVerificationExpiresAt?: string | null;
  passwordResetTokenHash?: string | null;
  passwordResetExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apps".
 */
export interface App {
  id: number;
  /**
   * Tenant workspace that owns this app. Legacy apps may remain empty until backfilled.
   */
  workspace?: (number | null) | Workspace;
  name: string;
  slug: string;
  /**
   * Globally unique key used by clean shared links. Exact aliases are platform-admin controlled; quick setup assigns a tenant-scoped key.
   */
  publicKey?: string | null;
  routingMode?: ('scheme-handoff' | 'verified-app-links') | null;
  description?: string | null;
  /**
   * Custom mobile URL scheme without ://. Required for new apps; legacy apps can be backfilled.
   */
  nativeScheme?: string | null;
  status: 'draft' | 'active' | 'paused';
  iosBundleId?: string | null;
  iosTeamId?: string | null;
  androidPackageName?: string | null;
  androidSha256CertFingerprints?: string[] | null;
  appStoreUrl?: string | null;
  playStoreUrl?: string | null;
  fallbackUrl?: string | null;
  /**
   * Hostnames permitted for per-link fallback overrides.
   */
  allowedFallbackHosts?: string[] | null;
  /**
   * Platform abuse hold. Tenant lifecycle changes cannot clear this control.
   */
  platformSuspended?: boolean | null;
  platformSuspendedAt?: string | null;
  platformRestoredAt?: string | null;
  platformSuspensionReason?: string | null;
  platformSuspensionCase?: (number | null) | AbuseCase;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces".
 */
export interface Workspace {
  id: number;
  organization: number | Organization;
  name: string;
  slug: string;
  status: 'active' | 'pending-verification' | 'suspended';
  /**
   * Platform abuse hold. Tenant lifecycle changes cannot clear this control.
   */
  platformSuspended?: boolean | null;
  platformSuspendedAt?: string | null;
  platformRestoredAt?: string | null;
  platformSuspensionReason?: string | null;
  platformSuspensionCase?: (number | null) | AbuseCase;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  slug: string;
  status: 'active' | 'pending-verification' | 'suspended';
  /**
   * Platform abuse hold. Tenant lifecycle changes cannot clear this control.
   */
  platformSuspended?: boolean | null;
  platformSuspendedAt?: string | null;
  platformRestoredAt?: string | null;
  platformSuspensionReason?: string | null;
  platformSuspensionCase?: (number | null) | AbuseCase;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abuse-cases".
 */
export interface AbuseCase {
  id: number;
  title: string;
  status: 'open' | 'investigating' | 'actioned' | 'closed';
  severity: 'low' | 'medium' | 'high' | 'critical';
  primaryReport?: (number | null) | AbuseReport;
  workspace?: (number | null) | Workspace;
  domain?: (number | null) | Domain;
  app?: (number | null) | App;
  link?: (number | null) | DeepLink;
  assignedTo?: (number | null) | User;
  openedAt: string;
  closedAt?: string | null;
  resolution?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abuse-reports".
 */
export interface AbuseReport {
  id: number;
  category: 'malware' | 'phishing' | 'spam' | 'impersonation' | 'other';
  targetHostname: string;
  targetPath?: string | null;
  details: string;
  reporterContact?: string | null;
  reporterKeyHash: string;
  userAgentHash?: string | null;
  submissionHash: string;
  receivedAt: string;
  status: 'received' | 'triaged' | 'attached-to-case' | 'closed';
  workspace?: (number | null) | Workspace;
  domain?: (number | null) | Domain;
  app?: (number | null) | App;
  link?: (number | null) | DeepLink;
  /**
   * Bounded identifiers captured at intake; no raw client IP is retained.
   */
  evidenceSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains".
 */
export interface Domain {
  id: number;
  workspace: number | Workspace;
  hostname: string;
  type: 'managed' | 'custom';
  status: 'pending-dns' | 'verifying' | 'certificate-ready' | 'association-incomplete' | 'active' | 'suspended';
  /**
   * Public DNS ownership challenge. Rotate by registering a new domain.
   */
  verificationToken: string;
  dnsVerifiedAt?: string | null;
  cnameVerifiedAt?: string | null;
  /**
   * Set only after the configured ingress reports certificate readiness.
   */
  tlsReadyAt?: string | null;
  /**
   * Opaque certificate-provider reference. Never exposed in tenant APIs.
   */
  tlsCertificateRef?: string | null;
  /**
   * Provider-reported certificate renewal instant.
   */
  tlsRenewsAt?: string | null;
  associationsVerifiedAt?: string | null;
  activatedAt?: string | null;
  lastCheckedAt?: string | null;
  lastVerificationError?: string | null;
  /**
   * Platform abuse hold. Tenant lifecycle changes cannot clear this control.
   */
  platformSuspended?: boolean | null;
  platformSuspendedAt?: string | null;
  platformRestoredAt?: string | null;
  platformSuspensionReason?: string | null;
  platformSuspensionCase?: (number | null) | AbuseCase;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-links".
 */
export interface DeepLink {
  id: number;
  name: string;
  app: number | App;
  slug: string;
  destinationPath: string;
  parameters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fallbackUrl?: string | null;
  status: 'draft' | 'active' | 'paused';
  expiresAt?: string | null;
  /**
   * Platform abuse hold. Tenant lifecycle changes cannot clear this control.
   */
  platformSuspended?: boolean | null;
  platformSuspendedAt?: string | null;
  platformRestoredAt?: string | null;
  platformSuspensionReason?: string | null;
  platformSuspensionCase?: (number | null) | AbuseCase;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fallback-origins".
 */
export interface FallbackOrigin {
  id: number;
  workspace: number | Workspace;
  hostname: string;
  status: 'pending' | 'verifying' | 'verified' | 'revoked';
  /**
   * Publish the generated TXT challenge to prove hostname ownership.
   */
  verificationToken: string;
  lastCheckedAt?: string | null;
  verifiedAt?: string | null;
  /**
   * Ownership proof must be renewed before this instant.
   */
  verificationExpiresAt?: string | null;
  /**
   * Bounded fail-safe grace after the proof expires, set only when the DNS provider is unavailable.
   */
  outageGraceExpiresAt?: string | null;
  revokedAt?: string | null;
  lastVerificationError?: string | null;
  /**
   * Bounded, provider-neutral DNS evidence hashes; raw TXT values are not stored.
   */
  lastEvidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fallback-url-safety-assessments".
 */
export interface FallbackUrlSafetyAssessment {
  id: number;
  workspace: number | Workspace;
  origin: number | FallbackOrigin;
  canonicalUrl: string;
  hostname: string;
  urlHash: string;
  status: 'pending' | 'checking' | 'safe' | 'unsafe' | 'error';
  checkedAt?: string | null;
  expiresAt?: string | null;
  providerObservedAt?: string | null;
  claimToken?: string | null;
  claimExpiresAt?: string | null;
  lastAttemptAt?: string | null;
  redirectCount: number;
  threats?: ('malware' | 'phishing' | 'social-engineering' | 'unwanted-software' | 'other')[] | null;
  lastError?: string | null;
  evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-invitations".
 */
export interface OrganizationInvitation {
  id: number;
  organization: number | Organization;
  emailNormalized: string;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  status: 'pending' | 'accepted' | 'revoked';
  tokenHash: string;
  expiresAt: string;
  deliveryMode: 'webhook' | 'manual';
  deliveredAt?: string | null;
  acceptedAt?: string | null;
  revokedAt?: string | null;
  invitedBy: number | User;
  acceptedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-memberships".
 */
export interface OrganizationMembership {
  id: number;
  organization: number | Organization;
  user: number | User;
  role: 'owner' | 'admin' | 'member' | 'viewer';
  status: 'active' | 'disabled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  organization: number | Organization;
  plan: 'free' | 'starter' | 'pro';
  status: 'active' | 'trialing' | 'past-due' | 'paused' | 'canceled';
  provider: string;
  providerCustomerID?: string | null;
  providerSubscriptionID: string;
  currentPeriodEnd?: string | null;
  graceEndsAt?: string | null;
  lastEventAt: string;
  lastProviderEventID: string;
  catalogVersion: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-events".
 */
export interface BillingEvent {
  id: number;
  organization: number | Organization;
  provider: string;
  providerEventID: string;
  providerSubscriptionID: string;
  occurredAt: string;
  receivedAt: string;
  payloadHash: string;
  plan: 'free' | 'starter' | 'pro';
  status: 'active' | 'trialing' | 'past-due' | 'paused' | 'canceled';
  outcome: 'applied' | 'stale';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-counters".
 */
export interface UsageCounter {
  id: number;
  organization: number | Organization;
  metric: 'monthly-resolutions';
  periodStart: string;
  count: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enforcement-events".
 */
export interface EnforcementEvent {
  id: number;
  resourceType: 'organization' | 'workspace' | 'domain' | 'app' | 'link';
  resourceID: string;
  action: 'suspend' | 'restore';
  previousSuspended: boolean;
  reason: string;
  abuseCase?: (number | null) | AbuseCase;
  actor: number | User;
  occurredAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abuse-case-events".
 */
export interface AbuseCaseEvent {
  id: number;
  abuseCase: number | AbuseCase;
  eventType: 'opened' | 'note' | 'status-changed' | 'resource-suspended' | 'resource-restored';
  summary: string;
  actor: number | User;
  enforcementEvent?: (number | null) | EnforcementEvent;
  occurredAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link-events".
 */
export interface LinkEvent {
  id: number;
  link: number | DeepLink;
  app: number | App;
  eventType: 'resolved' | 'fallback-viewed' | 'open-app-clicked' | 'store-clicked' | 'app-opened';
  platform: 'ios' | 'android' | 'web' | 'unknown';
  hostname?: string | null;
  sessionHash?: string | null;
  referrer?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-runs".
 */
export interface VerificationRun {
  id: number;
  app: number | App;
  link?: (number | null) | DeepLink;
  kind: 'association' | 'deep-link';
  status: 'queued' | 'running' | 'passed' | 'failed';
  checks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startedAt: string;
  finishedAt?: string | null;
  initiatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'deliver-cloud-account-email';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'deliver-cloud-account-email') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'workspaces';
        value: number | Workspace;
      } | null)
    | ({
        relationTo: 'domains';
        value: number | Domain;
      } | null)
    | ({
        relationTo: 'fallback-origins';
        value: number | FallbackOrigin;
      } | null)
    | ({
        relationTo: 'fallback-url-safety-assessments';
        value: number | FallbackUrlSafetyAssessment;
      } | null)
    | ({
        relationTo: 'organization-invitations';
        value: number | OrganizationInvitation;
      } | null)
    | ({
        relationTo: 'organization-memberships';
        value: number | OrganizationMembership;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'billing-events';
        value: number | BillingEvent;
      } | null)
    | ({
        relationTo: 'usage-counters';
        value: number | UsageCounter;
      } | null)
    | ({
        relationTo: 'apps';
        value: number | App;
      } | null)
    | ({
        relationTo: 'deep-links';
        value: number | DeepLink;
      } | null)
    | ({
        relationTo: 'abuse-reports';
        value: number | AbuseReport;
      } | null)
    | ({
        relationTo: 'abuse-cases';
        value: number | AbuseCase;
      } | null)
    | ({
        relationTo: 'enforcement-events';
        value: number | EnforcementEvent;
      } | null)
    | ({
        relationTo: 'abuse-case-events';
        value: number | AbuseCaseEvent;
      } | null)
    | ({
        relationTo: 'link-events';
        value: number | LinkEvent;
      } | null)
    | ({
        relationTo: 'verification-runs';
        value: number | VerificationRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  allowedApps?: T;
  emailVerificationTokenHash?: T;
  emailVerificationExpiresAt?: T;
  passwordResetTokenHash?: T;
  passwordResetExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  platformSuspended?: T;
  platformSuspendedAt?: T;
  platformRestoredAt?: T;
  platformSuspensionReason?: T;
  platformSuspensionCase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workspaces_select".
 */
export interface WorkspacesSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  slug?: T;
  status?: T;
  platformSuspended?: T;
  platformSuspendedAt?: T;
  platformRestoredAt?: T;
  platformSuspensionReason?: T;
  platformSuspensionCase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains_select".
 */
export interface DomainsSelect<T extends boolean = true> {
  workspace?: T;
  hostname?: T;
  type?: T;
  status?: T;
  verificationToken?: T;
  dnsVerifiedAt?: T;
  cnameVerifiedAt?: T;
  tlsReadyAt?: T;
  tlsCertificateRef?: T;
  tlsRenewsAt?: T;
  associationsVerifiedAt?: T;
  activatedAt?: T;
  lastCheckedAt?: T;
  lastVerificationError?: T;
  platformSuspended?: T;
  platformSuspendedAt?: T;
  platformRestoredAt?: T;
  platformSuspensionReason?: T;
  platformSuspensionCase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fallback-origins_select".
 */
export interface FallbackOriginsSelect<T extends boolean = true> {
  workspace?: T;
  hostname?: T;
  status?: T;
  verificationToken?: T;
  lastCheckedAt?: T;
  verifiedAt?: T;
  verificationExpiresAt?: T;
  outageGraceExpiresAt?: T;
  revokedAt?: T;
  lastVerificationError?: T;
  lastEvidence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fallback-url-safety-assessments_select".
 */
export interface FallbackUrlSafetyAssessmentsSelect<T extends boolean = true> {
  workspace?: T;
  origin?: T;
  canonicalUrl?: T;
  hostname?: T;
  urlHash?: T;
  status?: T;
  checkedAt?: T;
  expiresAt?: T;
  providerObservedAt?: T;
  claimToken?: T;
  claimExpiresAt?: T;
  lastAttemptAt?: T;
  redirectCount?: T;
  threats?: T;
  lastError?: T;
  evidence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-invitations_select".
 */
export interface OrganizationInvitationsSelect<T extends boolean = true> {
  organization?: T;
  emailNormalized?: T;
  role?: T;
  status?: T;
  tokenHash?: T;
  expiresAt?: T;
  deliveryMode?: T;
  deliveredAt?: T;
  acceptedAt?: T;
  revokedAt?: T;
  invitedBy?: T;
  acceptedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-memberships_select".
 */
export interface OrganizationMembershipsSelect<T extends boolean = true> {
  organization?: T;
  user?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  organization?: T;
  plan?: T;
  status?: T;
  provider?: T;
  providerCustomerID?: T;
  providerSubscriptionID?: T;
  currentPeriodEnd?: T;
  graceEndsAt?: T;
  lastEventAt?: T;
  lastProviderEventID?: T;
  catalogVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-events_select".
 */
export interface BillingEventsSelect<T extends boolean = true> {
  organization?: T;
  provider?: T;
  providerEventID?: T;
  providerSubscriptionID?: T;
  occurredAt?: T;
  receivedAt?: T;
  payloadHash?: T;
  plan?: T;
  status?: T;
  outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-counters_select".
 */
export interface UsageCountersSelect<T extends boolean = true> {
  organization?: T;
  metric?: T;
  periodStart?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apps_select".
 */
export interface AppsSelect<T extends boolean = true> {
  workspace?: T;
  name?: T;
  slug?: T;
  publicKey?: T;
  routingMode?: T;
  description?: T;
  nativeScheme?: T;
  status?: T;
  iosBundleId?: T;
  iosTeamId?: T;
  androidPackageName?: T;
  androidSha256CertFingerprints?: T;
  appStoreUrl?: T;
  playStoreUrl?: T;
  fallbackUrl?: T;
  allowedFallbackHosts?: T;
  platformSuspended?: T;
  platformSuspendedAt?: T;
  platformRestoredAt?: T;
  platformSuspensionReason?: T;
  platformSuspensionCase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deep-links_select".
 */
export interface DeepLinksSelect<T extends boolean = true> {
  name?: T;
  app?: T;
  slug?: T;
  destinationPath?: T;
  parameters?: T;
  fallbackUrl?: T;
  status?: T;
  expiresAt?: T;
  platformSuspended?: T;
  platformSuspendedAt?: T;
  platformRestoredAt?: T;
  platformSuspensionReason?: T;
  platformSuspensionCase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abuse-reports_select".
 */
export interface AbuseReportsSelect<T extends boolean = true> {
  category?: T;
  targetHostname?: T;
  targetPath?: T;
  details?: T;
  reporterContact?: T;
  reporterKeyHash?: T;
  userAgentHash?: T;
  submissionHash?: T;
  receivedAt?: T;
  status?: T;
  workspace?: T;
  domain?: T;
  app?: T;
  link?: T;
  evidenceSnapshot?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abuse-cases_select".
 */
export interface AbuseCasesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  severity?: T;
  primaryReport?: T;
  workspace?: T;
  domain?: T;
  app?: T;
  link?: T;
  assignedTo?: T;
  openedAt?: T;
  closedAt?: T;
  resolution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enforcement-events_select".
 */
export interface EnforcementEventsSelect<T extends boolean = true> {
  resourceType?: T;
  resourceID?: T;
  action?: T;
  previousSuspended?: T;
  reason?: T;
  abuseCase?: T;
  actor?: T;
  occurredAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abuse-case-events_select".
 */
export interface AbuseCaseEventsSelect<T extends boolean = true> {
  abuseCase?: T;
  eventType?: T;
  summary?: T;
  actor?: T;
  enforcementEvent?: T;
  occurredAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "link-events_select".
 */
export interface LinkEventsSelect<T extends boolean = true> {
  link?: T;
  app?: T;
  eventType?: T;
  platform?: T;
  hostname?: T;
  sessionHash?: T;
  referrer?: T;
  userAgent?: T;
  metadata?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-runs_select".
 */
export interface VerificationRunsSelect<T extends boolean = true> {
  app?: T;
  link?: T;
  kind?: T;
  status?: T;
  checks?: T;
  startedAt?: T;
  finishedAt?: T;
  initiatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDeliver-cloud-account-email".
 */
export interface TaskDeliverCloudAccountEmail {
  input: {
    encryptedEnvelope: string;
    expiresAt: string;
  };
  output: {
    delivered: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}